<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="15" passed="8" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-19T19:01:21 GMT+07:00" name="Default suite" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="207">
    <groups>
    </groups>
    <test started-at="2022-02-19T19:01:21 GMT+07:00" name="Default test" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="207">
      <class name="MinAgeTest">
        <test-method signature="minAgeTest(int,[LStudent;)[pri:0, instance:MinAgeTest@15b986cd, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="minAgeTest" data-provider="minAgeTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[LStudent;@6f952d6c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- minAgeTest -->
      </class> <!-- MinAgeTest -->
      <class name="LastNameTest">
        <test-method signature="lastName(java.lang.String,Student)[pri:0, instance:LastNameTest@76f10035, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="lastName" data-provider="lastNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="19" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sidorova]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@653f9805]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastName -->
        <test-method signature="lastName(java.lang.String,Student)[pri:0, instance:LastNameTest@76f10035, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="lastName" data-provider="lastNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="20" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Petrow-Ivanov]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@1ff623d]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Petrow-ivanov] but found [Petrow-Ivanov]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Petrow-ivanov] but found [Petrow-Ivanov]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at LastNameTest.lastName(TestNGFactory.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastName -->
        <test-method signature="lastName(java.lang.String,Student)[pri:0, instance:LastNameTest@76f10035, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="lastName" data-provider="lastNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="20" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[G]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@44717adb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [g] but found [G]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [g] but found [G]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at LastNameTest.lastName(TestNGFactory.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastName -->
      </class> <!-- LastNameTest -->
      <class name="FirstNameTest">
        <test-method signature="firstName(java.lang.String,Student)[pri:0, instance:FirstNameTest@5fa47fea, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="firstName" data-provider="firstNamesProvider" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ivan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@35c92995]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstName -->
        <test-method signature="firstName(java.lang.String,Student)[pri:0, instance:FirstNameTest@5fa47fea, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="firstName" data-provider="firstNamesProvider" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[N]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@2c8eadd5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstName -->
        <test-method signature="firstName(java.lang.String,Student)[pri:0, instance:FirstNameTest@5fa47fea, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="firstName" data-provider="firstNamesProvider" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="3" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Maria-Antuanetta]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@3ec8b056]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Maria-antuanetta] but found [Maria-Antuanetta]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Maria-antuanetta] but found [Maria-Antuanetta]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at FirstNameTest.firstName(TestNGFactory.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstName -->
      </class> <!-- FirstNameTest -->
      <class name="MaxAgeTest">
        <test-method signature="maxAgeTest(int,[LStudent;)[pri:0, instance:MaxAgeTest@41c62850, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="maxAgeTest" data-provider="maxAgeTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[40]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[LStudent;@4784013e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- maxAgeTest -->
      </class> <!-- MaxAgeTest -->
      <class name="AgeAvgTest">
        <test-method signature="avgAgeTest(int,[LStudent;)[pri:0, instance:AgeAvgTest@2b50150, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="avgAgeTest" data-provider="ageAvgTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="13" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[LStudent;@3a91d146]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- avgAgeTest -->
      </class> <!-- AgeAvgTest -->
      <class name="GetFullNameTest">
        <test-method signature="getFulltName(java.lang.String,Student)[pri:0, instance:GetFullNameTest@6b530eb9, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="getFulltName" data-provider="getFulltNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="2" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ivan Grib]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@40eef744]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Grib Ivan] but found [Ivan Grib]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Grib Ivan] but found [Ivan Grib]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at GetFullNameTest.getFulltName(TestNGFactory.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFulltName -->
        <test-method signature="getFulltName(java.lang.String,Student)[pri:0, instance:GetFullNameTest@6b530eb9, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="getFulltName" data-provider="getFulltNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="2" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Nicola Ivanov]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@32903c43]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ivanov Nicola] but found [Nicola Ivanov]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ivanov Nicola] but found [Nicola Ivanov]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at GetFullNameTest.getFulltName(TestNGFactory.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFulltName -->
        <test-method signature="getFulltName(java.lang.String,Student)[pri:0, instance:GetFullNameTest@6b530eb9, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="getFulltName" data-provider="getFulltNameTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="3" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Maria Sidorova]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@5a2a159b]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sidorova Maria] but found [Maria Sidorova]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sidorova Maria] but found [Maria Sidorova]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at GetFullNameTest.getFulltName(TestNGFactory.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFulltName -->
      </class> <!-- GetFullNameTest -->
      <class name="AgeTest">
        <test-method signature="age(int,Student)[pri:0, instance:AgeTest@4f8caaf3, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="age" data-provider="ageTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@1eb5a23f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- age -->
        <test-method signature="age(int,Student)[pri:0, instance:AgeTest@4f8caaf3, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="age" data-provider="ageTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@47c0245]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- age -->
        <test-method signature="age(int,Student)[pri:0, instance:AgeTest@4f8caaf3, instance params:[]]" started-at="2022-02-19T19:01:21 GMT+07:00" name="age" data-provider="ageTest" finished-at="2022-02-19T19:01:21 GMT+07:00" duration-ms="15" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Student@5dd157b6]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [18] but found [50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at AgeTest.age(TestNGFactory.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- age -->
      </class> <!-- AgeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
